# ===================================================================
# Spring Boot configuration for the "secret-samples" profile.
#
# This configuration overrides the application.yml file.
#
# More information on profiles: https://www.jhipster.tech/profiles/
# More information on configuration properties: https://www.jhipster.tech/common-application-properties/
# ===================================================================

# ===================================================================
# Samples for required secrets to be used in development and ci using prod profile.
# ===================================================================

spring:
  datasource:
    username: oncall
    password:

jhipster:
  security:
    authentication:
      jwt:
        base64-secret: NTkxMTE1OWExM2M5MzMyZDk5MGUyMTRkYmExYTk5MDBiMzQ5Mzk4MWQxNTI1MmY4ODIwMGRlY2NlNGRlNWUxMTYzMjU5ODBhNmRiN2IyYmExNTE5MGZlMjMzOGViNTdkOThiZGE2N2Y1MzkwMzU4ZmUzZDM2N2U2NWVhYjhhODA=
