package ar.edu.um.isa.oncall.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class AsignacionDeAccionAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAsignacionDeAccionAllPropertiesEquals(AsignacionDeAccion expected, AsignacionDeAccion actual) {
        assertAsignacionDeAccionAutoGeneratedPropertiesEquals(expected, actual);
        assertAsignacionDeAccionAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAsignacionDeAccionAllUpdatablePropertiesEquals(AsignacionDeAccion expected, AsignacionDeAccion actual) {
        assertAsignacionDeAccionUpdatableFieldsEquals(expected, actual);
        assertAsignacionDeAccionUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAsignacionDeAccionAutoGeneratedPropertiesEquals(AsignacionDeAccion expected, AsignacionDeAccion actual) {
        assertThat(actual)
            .as("Verify AsignacionDeAccion auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAsignacionDeAccionUpdatableFieldsEquals(AsignacionDeAccion expected, AsignacionDeAccion actual) {
        assertThat(actual)
            .as("Verify AsignacionDeAccion relevant properties")
            .satisfies(a -> assertThat(a.getTitulo()).as("check titulo").isEqualTo(expected.getTitulo()))
            .satisfies(a -> assertThat(a.getDescripcion()).as("check descripcion").isEqualTo(expected.getDescripcion()))
            .satisfies(a -> assertThat(a.getFechaVencimiento()).as("check fechaVencimiento").isEqualTo(expected.getFechaVencimiento()))
            .satisfies(a -> assertThat(a.getEstado()).as("check estado").isEqualTo(expected.getEstado()))
            .satisfies(a -> assertThat(a.getCreadaEn()).as("check creadaEn").isEqualTo(expected.getCreadaEn()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAsignacionDeAccionUpdatableRelationshipsEquals(AsignacionDeAccion expected, AsignacionDeAccion actual) {
        assertThat(actual)
            .as("Verify AsignacionDeAccion relationships")
            .satisfies(a -> assertThat(a.getAccionCorrectiva()).as("check accionCorrectiva").isEqualTo(expected.getAccionCorrectiva()));
    }
}
