package ar.edu.um.isa.oncall.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class CierreDeAccionAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCierreDeAccionAllPropertiesEquals(CierreDeAccion expected, CierreDeAccion actual) {
        assertCierreDeAccionAutoGeneratedPropertiesEquals(expected, actual);
        assertCierreDeAccionAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCierreDeAccionAllUpdatablePropertiesEquals(CierreDeAccion expected, CierreDeAccion actual) {
        assertCierreDeAccionUpdatableFieldsEquals(expected, actual);
        assertCierreDeAccionUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCierreDeAccionAutoGeneratedPropertiesEquals(CierreDeAccion expected, CierreDeAccion actual) {
        assertThat(actual)
            .as("Verify CierreDeAccion auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCierreDeAccionUpdatableFieldsEquals(CierreDeAccion expected, CierreDeAccion actual) {
        assertThat(actual)
            .as("Verify CierreDeAccion relevant properties")
            .satisfies(a -> assertThat(a.getComentarioCierre()).as("check comentarioCierre").isEqualTo(expected.getComentarioCierre()))
            .satisfies(a -> assertThat(a.getCerradoEn()).as("check cerradoEn").isEqualTo(expected.getCerradoEn()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCierreDeAccionUpdatableRelationshipsEquals(CierreDeAccion expected, CierreDeAccion actual) {
        assertThat(actual)
            .as("Verify CierreDeAccion relationships")
            .satisfies(a -> assertThat(a.getAsignacion()).as("check asignacion").isEqualTo(expected.getAsignacion()));
    }
}
