package ar.edu.um.isa.oncall.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class RecordatorioDeAccionAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRecordatorioDeAccionAllPropertiesEquals(RecordatorioDeAccion expected, RecordatorioDeAccion actual) {
        assertRecordatorioDeAccionAutoGeneratedPropertiesEquals(expected, actual);
        assertRecordatorioDeAccionAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRecordatorioDeAccionAllUpdatablePropertiesEquals(RecordatorioDeAccion expected, RecordatorioDeAccion actual) {
        assertRecordatorioDeAccionUpdatableFieldsEquals(expected, actual);
        assertRecordatorioDeAccionUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRecordatorioDeAccionAutoGeneratedPropertiesEquals(RecordatorioDeAccion expected, RecordatorioDeAccion actual) {
        assertThat(actual)
            .as("Verify RecordatorioDeAccion auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRecordatorioDeAccionUpdatableFieldsEquals(RecordatorioDeAccion expected, RecordatorioDeAccion actual) {
        assertThat(actual)
            .as("Verify RecordatorioDeAccion relevant properties")
            .satisfies(a -> assertThat(a.getMensaje()).as("check mensaje").isEqualTo(expected.getMensaje()))
            .satisfies(a -> assertThat(a.getEnviadoEn()).as("check enviadoEn").isEqualTo(expected.getEnviadoEn()))
            .satisfies(a -> assertThat(a.getNivelEscalamiento()).as("check nivelEscalamiento").isEqualTo(expected.getNivelEscalamiento()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRecordatorioDeAccionUpdatableRelationshipsEquals(RecordatorioDeAccion expected, RecordatorioDeAccion actual) {
        assertThat(actual)
            .as("Verify RecordatorioDeAccion relationships")
            .satisfies(a -> assertThat(a.getAsignacion()).as("check asignacion").isEqualTo(expected.getAsignacion()));
    }
}
